server:
  port: 6006

spring:
  application:
    name: scorpio-stream-6006  #consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: b-2.testing-kafka.wfj7d6.c3.kafka.us-west-2.amazonaws.com:9092         #Kafka的消息中间件服务器
          zk-nodes: 172.21.31.24:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        input:
          destination:  stream-demo-trans # 6004消息中转换了一下名字  stream-demo
        myInput:
          destination: stream-my-demo

eureka:
  client:
   service-url:
    defaultZone: http://server1:7001/eureka/







