server:
  port: 6003
spring:
  application:
    name: scorpio-stream-6003  #producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: b-2.testing-kafka.wfj7d6.c3.kafka.us-west-2.amazonaws.com:9092         #Kafka的消息中间件服务器
          zk-nodes: 172.21.31.24:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        output:      #这里用stream给我们提供的默认output，后面会讲到自定义output
          destination: stream-demo    #消息发往的目的地
          content-type: text/plain    #消息发送的格式，接收端不用指定格式，但是发送端要
        myOutput:
          destination: stream-my-demo
          content-type: text/plain

eureka:
  client:
   service-url:
    defaultZone: http://server1:7001/eureka/









